### ISSUE TITLE
Trigger lose condition when number of steps left is zero

### ISSUE THREAD

**Issue by heldderarbeit** [tfuxu/floodit#8]
Currently you don't lose automatically when the counter of steps left reaches 0. You also have to press a color button before the "You Lost!" window is shown.
[Screencast from 2024-09-19 19-22-57.webm](https://github.com/user-attachments/assets/e04dbbf4-cb3e-44bb-b9ff-e63608a3bf1a)

In my opinion, if the counter shows that you have zero steps left, it should not be possible to take any action like triggering a coloring action (since that is a contradictory statement). The last possibility for pressing a color button should be when the counter is showing: "1 Steps Left".

**Comment by tfuxu** [comment]
I'll see what can be done
